FROM fluent/fluentd:v0.12.36

RUN gem install fluent-plugin-multiprocess --no-rdoc --no-ri
RUN gem install fluent-plugin-forest --no-rdoc --no-ri
RUN gem install fluent-plugin-rewrite-tag-filter --no-rdoc --no-ri
